# Generated by Django 5.2.6 on 2025-10-08 01:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_product_brand_id_alter_product_category_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="seo_keywords_ids",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
